## Data Types & Attributes


In [1]:
# Q1
import numpy as np
arr = np.arange(6)
print(arr.dtype)

int32


In [2]:
# Q2
arr = np.array([1.0, 2.0])
print(arr.dtype == np.float64)

True


In [3]:
# Q3
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

In [4]:
# Q4
arr = np.array([1, 2, 3])
arr = arr.astype(np.float32)

In [5]:
# Q5
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)

In [6]:
# Q6
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

In [7]:
# Q7
def array_dimension(arr):
    return arr.ndim

In [8]:
# Q8
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

In [9]:
# Q9
def array_strides(arr):
    return arr.strides

In [10]:
# Q10
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

## Array Creation


In [11]:
# Q11
def create_zeros_array(n):
    return np.zeros(n)

In [12]:
# Q12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [13]:
# Q13
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [14]:
# Q14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [15]:
# Q15
def create_identity_matrix(n):
    return np.eye(n)

In [16]:
# Q16
def list_to_array(lst):
    return np.array(lst)

In [17]:
# Q17
arr = np.array([1, 2, 3, 4])
view = arr.view()

## Concatenation and Stacking


In [18]:
# Q18
def concat_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

In [19]:
# Q19
a = np.array([[1], [2]])
b = np.array([[3, 4], [5, 6]])
result = np.concatenate((a, b), axis=1)

In [20]:
# Q20
arrays = [np.array([1, 2]), np.array([3, 4])]
result = np.vstack(arrays)

## Array Generation


In [21]:
# Q21
def generate_array_range(start, stop, step):
    return np.arange(start, stop + 1, step)

In [22]:
# Q22
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
# Q23
np.logspace(0, 3, 5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

## Pandas + NumPy


In [24]:
# Q24
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data)

In [25]:
# Q25
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

## Indexing and Slicing


In [26]:
# Q26
arr = np.array([1, 2, 3, 4, 5])
arr[2]

3

In [27]:
# Q27
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1, 2]

6

In [28]:
# Q28
arr = np.array([1, 6, 3, 8])
arr[arr > 5]

array([6, 8])

In [29]:
# Q29
arr = np.array([0, 1, 2, 3, 4, 5, 6])
arr[2:6]

array([2, 3, 4, 5])

In [30]:
# Q30
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[[0, 1], 1:3]

array([[2, 3],
       [5, 6]])

## Advanced Indexing


In [31]:
# Q31
arr = np.array([[1, 2], [3, 4]])
indices = [0, 1]
arr[indices]

array([[1, 2],
       [3, 4]])

In [32]:
# Q32
arr = np.array([1, 2, 10, 20])
arr[arr > 5]

array([10, 20])

In [33]:
# Q33
arr = np.arange(27).reshape(3, 3, 3)
arr[[0, 1], [1, 2], [2, 0]]

array([ 5, 15])

In [34]:
# Q34
arr = np.array([10, 20, 30, 40])
arr[(arr > 15) & (arr < 35)]

array([20, 30])

In [35]:
# Q35
arr = np.array([[10, 20, 30], [40, 50, 60]])
rows = [0, 1]
cols = [1, 2]
arr[rows, cols]

array([20, 60])

## Broadcasting


In [36]:
# Q36
arr = np.array([1, 2, 3])
arr + 5

array([6, 7, 8])

In [37]:
# Q37
a = np.arange(12).reshape(3, 4)
b = np.array([1, 2, 3])
result = a[:, :3] * b[:, np.newaxis]

In [38]:
# Q38
a = np.random.rand(4, 3)
b = np.random.rand(1, 4)
a + b.T

array([[1.47312446, 0.77846768, 1.29716089],
       [1.09294254, 1.24863367, 1.53384957],
       [1.14860019, 1.77594039, 1.61976024],
       [1.53251742, 1.10663846, 1.17558518]])

In [39]:
# Q39
a = np.ones((3, 1))
b = np.ones((1, 3))
a + b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [40]:
# Q40
# Incompatible shapes (2, 3) and (2, 2)
a = np.ones((2, 3))
b = np.ones((2, 2))
try:
    a * b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,2) 


## Aggregations and Statistics


In [41]:
# Q41
arr = np.random.rand(3, 3)
arr.mean(axis=0)

array([0.63140407, 0.45885352, 0.53296806])

In [42]:
# Q42
arr = np.random.rand(3, 3)
arr.max(axis=1)

array([0.95874765, 0.99176321, 0.83184165])

In [43]:
# Q43
arr = np.random.rand(3, 3)
arr.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [44]:
# Q44
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

In [45]:
# Q45
arr = np.array([[2, 4], [6, 8]])
np.all(arr % 2 == 0, axis=0)

array([ True,  True])

## Reshaping and Flattening


In [46]:
#Q46
arr = np.arange(12)
reshaped = arr.reshape(3, 4)


In [47]:
# Q47
# Code for Q47
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()


In [48]:
# Q48
# Code for Q48
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
concat_axis0 = np.concatenate((a, b), axis=0)
concat_axis1 = np.concatenate((a, b), axis=1)


In [49]:
# Q49
# Code for Q49
arr = np.arange(16).reshape(4, 4)
split_axis0 = np.split(arr, 2, axis=0)
split_axis1 = np.split(arr, 2, axis=1)


In [50]:
# Q50
# Code for Q50
arr = np.array([1, 2, 3, 4, 5])
inserted = np.insert(arr, 2, 99)
deleted = np.delete(arr, 1)


## Element-wise Operations


In [51]:
# Q51
# Code for Q51
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b


In [52]:
# Q52
# Code for Q52
sub = a - b


In [53]:
# Q53
# Code for Q53
mul = a * b


In [54]:
# Q54
# Code for Q54 
div = a / b



In [55]:
# Q55
# Code for Q55 
exp = a ** b


## String Operations


In [56]:
# Q56
# Code for Q56 
arr = np.array(['apple', 'banana', 'apple pie'])
count = np.char.count(arr, 'apple')


In [57]:
# Q57
# Code for Q57
arr = np.array(['HeLLo', 'WorLD'])
upper = np.char.array(arr)
uppercase_chars = np.char.replace(upper, r'[^A-Z]', '', regex=True)


TypeError: replace() got an unexpected keyword argument 'regex'

In [ ]:
# Q58
# Code for Q58
arr = np.array(['hello world', 'world map'])
replaced = np.char.replace(arr, 'world', 'Earth')


In [ ]:
# Q59
# Code for Q59
a = np.array(['Hello', 'Good'])
b = np.array(['World', 'Morning'])
concatenated = np.char.add(a, b)


In [ ]:
# Q60
# Code for Q60
arr = np.array(['short', 'muchlongerstring', 'mid'])
max_length = max(np.char.str_len(arr))


## Descriptive Statistics


In [ ]:
# Q61
# Code for Q61
arr = np.random.randint(1, 1001, 100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)


In [ ]:
# Q62
# Code for Q62
arr = np.random.randint(1, 101, 50)
p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)


In [ ]:
# Q63
# Code for Q63
x = np.random.rand(10)
y = np.random.rand(10)
corr = np.corrcoef(x, y)


In [ ]:
# Q64
# Code for Q64
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
dot = np.dot(a, b)


In [ ]:
# Q65
# Code for Q65
arr = np.random.randint(1, 100, 50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)


## Search and Sort


In [ ]:
# Q66
# Code for Q66
arr = np.array([10, 20, 30, 40])
index = np.where(arr == 30)[0][0]


In [ ]:
# Q67
# Code for Q67
arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(arr)


In [ ]:
# Q68
# Code for Q68
filtered = arr[arr > 20]


In [ ]:
# Q69
# Code for Q69
filtered = arr[arr % 3 == 0]


In [ ]:
# Q70
# Code for Q70
filtered = arr[(arr >= 20) & (arr <= 40)]


## Byte Order & Swapping


In [ ]:
# Q71
# Code for Q71
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder


In [ ]:
# Q72
# Code for Q72
arr.byteswap(inplace=True)
